# Generated by Django 3.0.3 on 2020-05-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
