# Generated by Django 3.0.3 on 2020-03-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='aboutus',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='references',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpemail',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtppassword',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpserver',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
