# Generated by Django 3.0.3 on 2020-05-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='masa_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
